# Generated by Django 5.1.5 on 2025-04-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_comment_approved_comment_alter_comment_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="approved_comment",
            field=models.BooleanField(default=False),
        ),
    ]
